### ISSUE TITLE
Test data download fails

### ISSUE THREAD

**Issue by pkopparla** [pka/georaster#1]
Hello,
This is what happens when I try to get the test data:
```
data % make
wget http://www.openmaps.online/eudem_download/N265E425.zip
make: wget: No such file or directory
```

**Comment by pka** [comment]
`wget` is a file downloading tool preinstalled on most  Linux distros. You can also download the file with a browser and store it in that directory. A new `make` will then do the next steps.

In the meantime there are smaller test images for running the tests.

**Comment by pkopparla** [comment]
My bad, sorry. I misread the error message and thought the file wasn't available. It works once wget is installed.

Another question, you said it'd be good to have an example for using the georaster API with imageops. Just trying to understand how that would work, first: open a big tiff file as GeoTiffReader. Then import into an image::ImageBuffer using one of the `from` methods?

**Comment by pka** [comment]
Yes, that's probably the way to do it. Creating an `image::ImageBuffer` or similar using the `points` iterator.

**Comment by pkopparla** [comment]
Got it, thanks. I'll create a PR in a couple of days if I can get it to work.
