### ISSUE TITLE
Adding example using imageops

### ISSUE THREAD

**Issue by pkopparla** [pka/georaster#2]
As discussed [here](https://github.com/pka/georaster/issues/1#issuecomment-1298297206), tried reading in `GeoTiffReader` to `image::ImageBuffer` but cannot seem to get it working with any of the `from` methods. Would you have a link to the `points` iterator? I couldn't find it in this repo or `image` or `tiff`.

Another interesting alternative might be to use [image::load](https://docs.rs/image/latest/image/fn.load.html).
But that would need `GeoTiffReader` to have the traits `Seek` and `BufRead`. Any thoughts?

**Comment by pka** [comment]
Added an example using image-rs in 6d593f6d403845f8380f56f5bb583401aea20c8c
